<div class="header">
    <div class="logo"><img src="https://106209751.github.io/Group-Projects/project1/images/Companylogo.png" alt="Company Logo" width="250" height="250"></div>
    <div><h1><strong>Home</strong></h1></div>
    <div>
        <nav>
            <a href="index.html">Home</a>
            <a href="jobs.html">Jobs</a>
            <a href="apply.html">Apply Here</a>
            <a href="about.html">About</a>
        </nav>
    </div>
</div>