<div class="header">
    <div class="logo"><img src="https://106209751.github.io/Group-Projects/project1/images/Companylogo.png" alt="Company Logo" width="250" height="250"></div>
    <div><h1><strong>Home</strong></h1></div>
    <div>
        <nav>
            <a href="index.php">Home</a>
            <a href="jobs.php">Jobs</a>
            <a href="apply.php">Apply Here</a>
            <a href="about.php">About</a>
        </nav>
    </div>
</div>